beatify standDerDinge and add some failure output

diff --git a/standDerDinge b/standDerDinge
--- a/standDerDinge
+++ b/standDerDinge
@@ -2,11 +2,49 @@
 
 today=$(date +%Y-%m-%d)
 yesterday=$(date +%Y-%m-%d -d yesterday)
-
+lastFriday=$(date +%Y-%m-%d -d 'last Friday')
 xmlFeed=http://pcast.sr-online.de/feeds/sr1standderdinge/feed.xml
+Green='\033[0;32m'
+Red='\033[0;31m'
+Blue='\033[0;34m'
+NC='\033[0m'
 
-#in Grep den Rueckgabewert testen fuer heute und gestern bzw vlt auch generell dann den Wochentag testen wenn gestern nicht geht weil die Sendung am Wochenden nicht stattfindet
+wget "$xmlFeed" -O feed.xml >/dev/null 2>/dev/null
 
-wget "$xmlFeed" -O feed.xml 
+if [ "$?" == 0 ]; then
+	echo -e "${Green}✔ Download of xml passed${NC} "
+else
+	echo -e "${Red}✗ Your download failed check your network connection${NC}"
+	exit 1
+fi
 
-echo `grep 2017-05-19 feed.xml  |grep mp3|grep link|cut -d'>' -f 2|cut -d'<' -f 1`
+grep "$today" feed.xml >/dev/null
+
+if [ "$?" == 0 ]; then 
+	mp3Link=$(grep "$today" feed.xml  | grep mp3 | grep link | cut -d'>' -f 2 | cut -d'<' -f 1)
+else
+	grep "$yesterday" feed.xml >/dev/null
+	
+	if [ "$?" == 0 ]; then
+		mp3Link=$(grep "$yesterday" feed.xml  | grep mp3 | grep link | cut -d'>' -f 2 | cut -d'<' -f 1)
+	elif [ "`date +%a -d yesterday`" == "So" ]; then
+		mp3Link=$(grep "$lastFriday" feed.xml  | grep mp3 | grep link | cut -d'>' -f 2 | cut -d'<' -f 1)
+	elif [ "`date +%a -d yesterday`" == "Sa" ]; then
+                mp3Link=$(grep "$lastFriday" feed.xml  | grep mp3 | grep link | cut -d'>' -f 2 | cut -d'<' -f 1)	
+	fi
+
+fi
+
+wget "$mp3Link" -O "StandDerDinge.mp3" >/dev/null 2>/dev/null
+
+if [ "$?" == 0 ]; then
+        echo -e "${Green}✔ Download of mp3 passed${NC} "
+	echo -e "${Blue}now you can hear your podcast with mplayer or vlc ${NC}" 
+else
+        echo -e "${Red}✗ Your download failed check your network connection${NC}"
+        exit 1
+fi
+
+
+
+rm feed.xml
